import { HANDLE_TYPE } from './handle'

const BIND_CANCEL_HANDLE_TYPE_SET = new Set([
  HANDLE_TYPE.MOVE,
  HANDLE_TYPE.ROTATE
])

const BIND_REPLACE_HANDLE_TYPE_SET = new Set([
  HANDLE_TYPE.TOP_FREE,
  HANDLE_TYPE.BOTTOM_FREE,
  HANDLE_TYPE.ANCHOR_HEAD,
  HANDLE_TYPE.ANCHOR_TAIL,
  HANDLE_TYPE.TOP_FREE_LINK,
  HANDLE_TYPE.BOTTOM_FREE_LINK,
  HANDLE_TYPE.ANCHOR_HEAD_LINK,
  HANDLE_TYPE.ANCHOR_TAIL_LINK
])

export {
  BIND_CANCEL_HANDLE_TYPE_SET,
  BIND_REPLACE_HANDLE_TYPE_SET
}
