import { HANDLE_TYPE } from './handle'

const SNAP_TYPE = {
  X_MIN: 'X_MIN',
  X_MID: 'X_MID',
  X_MAX: 'X_MAX',

  Y_MIN: 'Y_MIN',
  Y_MID: 'Y_MID',
  Y_MAX: 'Y_MAX',

  GAP_MID_X: 'GAP_MID_X', // means: widget - preview - widgetRef
  GAP_MID_Y: 'GAP_MID_Y',

  GAP_EXT_LEFT: 'GAP_EXT_LEFT', // means: preview - widgetRef - widget
  GAP_EXT_RIGHT: 'GAP_EXT_RIGHT', // means: widget - widgetRef - preview
  GAP_EXT_TOP: 'GAP_EXT_TOP',
  GAP_EXT_BOTTOM: 'GAP_EXT_BOTTOM'
}

const SNAP_TO_SET_MAP = {
  X_MIN: new Set([ SNAP_TYPE.X_MIN, SNAP_TYPE.X_MID, SNAP_TYPE.X_MAX, SNAP_TYPE.GAP_EXT_RIGHT ]),
  X_MID: new Set([ SNAP_TYPE.X_MIN, SNAP_TYPE.X_MID, SNAP_TYPE.X_MAX, SNAP_TYPE.GAP_MID_X ]),
  X_MAX: new Set([ SNAP_TYPE.X_MIN, SNAP_TYPE.X_MID, SNAP_TYPE.X_MAX, SNAP_TYPE.GAP_EXT_LEFT ]),

  Y_MIN: new Set([ SNAP_TYPE.Y_MIN, SNAP_TYPE.Y_MID, SNAP_TYPE.Y_MAX, SNAP_TYPE.GAP_EXT_BOTTOM ]),
  Y_MID: new Set([ SNAP_TYPE.Y_MIN, SNAP_TYPE.Y_MID, SNAP_TYPE.Y_MAX, SNAP_TYPE.GAP_MID_Y ]),
  Y_MAX: new Set([ SNAP_TYPE.Y_MIN, SNAP_TYPE.Y_MID, SNAP_TYPE.Y_MAX, SNAP_TYPE.GAP_EXT_TOP ])
}

const SNAP_ENABLED_HANDEL_TYPE_SET = new Set([
  HANDLE_TYPE.MOVE,

  HANDLE_TYPE.TOP_LEFT,
  HANDLE_TYPE.TOP,
  HANDLE_TYPE.TOP_RIGHT,
  HANDLE_TYPE.LEFT,
  HANDLE_TYPE.RIGHT,
  HANDLE_TYPE.BOTTOM_LEFT,
  HANDLE_TYPE.BOTTOM,
  HANDLE_TYPE.BOTTOM_RIGHT,

  HANDLE_TYPE.TOP_LEFT_ZOOM,
  HANDLE_TYPE.TOP_RIGHT_ZOOM,
  HANDLE_TYPE.BOTTOM_LEFT_ZOOM,
  HANDLE_TYPE.BOTTOM_RIGHT_ZOOM
])

export {
  SNAP_TYPE,
  SNAP_TO_SET_MAP,

  SNAP_ENABLED_HANDEL_TYPE_SET
}
